version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install -r requirements.txt
	  - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 723294176677.dkr.ecr.us-east-2.amazonaws.com
  pre_build:
    commands:
      - echo Iniciando a fase de pre_build...
  build:
    commands:
      - echo Iniciando a fase de build...
      - docker build -t kralen-web .
      - docker tag kralen-web:latest 723294176677.dkr.ecr.us-east-2.amazonaws.com/kralen-web:latest
  post_build:
    commands:
      - echo Fase de post_build concluída.
      - docker push 723294176677.dkr.ecr.us-east-2.amazonaws.com/kralen-web:latest

artifacts:
  files:
    - '**/*'
